name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows]
        profile: [release, dev]
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@master
      with:
        profile: minimal
        toolchain: beta
        override: true
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --profile ${{ matrix.profile }} --verbose